### ISSUE TITLE
no output files 

### ISSUE THREAD

**Issue by leeyoyohku** [deweylab/CellO#4]
Hi CellO team,

`Training classifier for label CL:0001058...
Number of positive items: 4
Number of negative items: 4249
(316/317)
Training classifier for label CL:0000767...
Number of positive items: 4
Number of negative items: 3696
(317/317)
Training classifier for label CL:0001044...
Number of positive items: 2
Number of negative items: 4032
done.
Writing trained model to cello.model.dill
Normalizing counts...
done.
Killed`

Thanks for contributing to this tool. I wanted to apply to a pbmc dataset (GSE144744), but found that there was no output files except a model.drill (~300M), and a cell.log folder containing only genes_absent_from_training_set.tsv. Seems it stopped from the normalization step seen above.

Looking forward to your reply.

**Comment by mbernste** [comment]
Hi,

Thanks for your interest in CellO!  Was there any traceback or error message, or is the text above the only output text?

I will try running it on GSE144744 to see if I can reproduce the error.

Matt

**Comment by mbernste** [comment]
Hi, is the file you're attempting to run CellO on the file consisting of ~500k cells?  If so, I would suspect that the program crashed due to the memory limit being reached. Unfortunately, we have not tested CellO on such a large dataset and I suspect that it is not currently set up for the task on so many cells.
